Deps: Update kotlin compile testing to 1.6.0 (tschuchortdev)
Release Notes: https://github.com/tschuchortdev/kotlin-compile-testing/
releases/tag/1.6.0

This update was done mainly due to the below library
related incompatibility while testing 'RemoteConfigProcessorTest':

e: Incompatible classes were found in dependencies. Remove them from the
 classpath or use '-Xskip-metadata-version-check' to suppress errors
e: file:///.../Feature.kt:3:41 Class 'org.wordpress.android.annotation
 .Feature' was compiled with an incompatible version of Kotlin. The
 binary version of its metadata is 2.0.0, expected version is 1.8.0.
The class is loaded from /Users/.../WordPress-Android/libs/annotations/
 build/libs/annotations.jar!/org/wordpress/android/annotation/
 Feature.class

------------------------------------------------------------------------

Otherwise, this is done because 'RemoteConfigProcessorTest' was failing
with the below 1 x 'ClassNotFoundException' exception:

RemoteConfigProcessorTest > given class with feature in development
 annotation, when compiling, generate expected list of classes FAILED
    java.lang.ClassNotFoundException at RemoteConfigProcessorTest.kt:107

------------------------------------------------------------------------

While also, 'RemoteConfigProcessorTest' was failing with the below 3 x
'ComparisonFailure' test failures:

RemoteConfigProcessorTest > given a class with remote field annotation,
 when compiling, generate expected config defaults class FAILED
    org.junit.ComparisonFailure at RemoteConfigProcessorTest.kt:40

RemoteConfigProcessorTest > given a class with features annotation,
 when compiling, generate expected configuration check FAILED
    org.junit.ComparisonFailure at RemoteConfigProcessorTest.kt:18

RemoteConfigProcessorTest > given class with feature and experiment
 annotation, when compiling, generate config defaults class FAILED
    org.junit.ComparisonFailure at RemoteConfigProcessorTest.kt:70

------------------------------------------------------------------------

No matter, even after updating the library, the required
'ExperimentalCompilerApi' got added on 'RemoteConfigProcessorTest' to
fix a number of  'Experimental API' errors such as the below:

"This API is experimental. There are no stability guarantees for it"

As well as adding the 'UnsafeCastFunction' annotation to fix the below
3 x 'UNCHECKED_CAST'  errors:

------------------------------------------------------------------------

> Task :libs:processors:compileTestKotlin FAILED
e: file:///Users/.../WordPress-Android/libs/processors/src/test/kotlin/
 org/wordpress/android/processor/RemoteConfigProcessorTest.kt:53:18
        Usage of this function is unsafe because it does not have native
         compiler support
         This means that compiler won't report UNCHECKED_CAST,
          CAST_NEVER_SUCCEED or similar
         diagnostics in case of error cast (which can happen immediately
          or after some
         refactoring of class hierarchy)
        Consider using regular `as` and `as?`

e: file:///Users/.../WordPress-Android/libs/processors/src/test/kotlin/
 org/wordpress/android/processor/RemoteConfigProcessorTest.kt:83:18
        Usage of this function is unsafe because it does not have native
         compiler support
         This means that compiler won't report UNCHECKED_CAST,
          CAST_NEVER_SUCCEED or similar
         diagnostics in case of error cast (which can happen immediately
          or after some
         refactoring of class hierarchy)
        Consider using regular `as` and `as?`

e: file:///Users/.../WordPress-Android/libs/processors/src/test/kotlin/
 org/wordpress/android/processor/RemoteConfigProcessorTest.kt:117:18
        Usage of this function is unsafe because it does not have native
         compiler support
         This means that compiler won't report UNCHECKED_CAST,
          CAST_NEVER_SUCCEED or similar
         diagnostics in case of error cast (which can happen immediately
          or after some
         refactoring of class hierarchy)
        Consider using regular `as` and `as?`

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libs:processors:compileTestKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner
 .GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details