Deps: Add compose compile gradle plugin
Starting in Kotlin 2.0, the Compose Compiler Gradle plugin is required
when compose is enabled. This change addresses that, along with removing
the oudated 'androidx-compose-compiler' configuration.

------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':WordPress'.
> com.android.builder.errors.EvalIssueException: Starting in Kotlin 2.0,
   the Compose Compiler Gradle plugin is required
  when compose is enabled. See the following link for more information:
  https://d.android.com/r/studio-ui/compose-compiler